services:
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: gunicorn config.wsgi:application --bind=0.0.0.0:8000 --timeout=120 --workers=3
    volumes:
      - ./backend:/backend
      - ./backend/staticfiles:/backend/staticfiles
      # - /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/3b9c32c360ea73a3fd7ff5be377a79367da580e2d9691c18565bdf836a761bc9:/backend:rw
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DJANGO_ALLOWED_HOST=localhost
      - DATABASE_URL=mysql://takato:0605@db:3306/todo
      - DATABASE_NAME=todo
      - DATABASE_USER=takato
      - DATABASE_PASSWORD=0605
      - DATABASE_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo-networks
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    command: npm run serve
    volumes:
      - ./frontend/todo:/backend/todo
      # - ./frontend:/todo
    ports:
      - "8080:8080"
    networks:
      - todo-networks
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=20050605
      - MYSQL_USER=takato
      - MYSQL_DATABASE=todo
      - MYSQL_PASSWORD=0605
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - todo-networks
    
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/staticfiles:/backend/staticfiles
      - ./todo/dist:/usr/share/nginx/html
    depends_on: 
      - backend
      - frontend
    networks: 
      - todo-networks
volumes:
  mysql_data:
networks:
  todo-networks:
    driver: bridge